name: Deploy website to Netlify and build notebooks

on:
 pull_request:
   branches:
     - main
     - master
     - dev
     - light-action

#on:
#  push:
#    branches:
#      - main
#      - master
#      - light-action

jobs:
  markdownise-manipulation:
    name: Partie manipulation
    runs-on: ubuntu-latest
    container: linogaliana/python-datascientist:manipulation
    steps:
      - uses: linogaliana/python-datascientist-actions/compile@v1.0.120
        with:
          directory-name: 'manipulation'
  markdownise-visualisation:
    name: Partie visualisation
    runs-on: ubuntu-latest
    container: linogaliana/python-datascientist:visualisation
    steps:
      - uses: linogaliana/python-datascientist-actions/compile@v1.0.120
        with:
          directory-name: 'visualisation'
  markdownise-modelisation:
    name: Partie modélisation
    runs-on: ubuntu-latest
    container: linogaliana/python-datascientist:modelisation
    steps:
      - uses: linogaliana/python-datascientist-actions/compile@v1.0.120
        with:
          directory-name: 'modelisation'
  markdownise-nlp:
    name: Partie NLP
    runs-on: ubuntu-latest
    container: linogaliana/python-datascientist:nlp
    steps:
      - uses: linogaliana/python-datascientist-actions/compile@v1.0.120
        with:
          directory-name: 'NLP'
  markdownise-reste:
    name: Markdown non thématiques
    runs-on: ubuntu-latest
    container: linogaliana/python-datascientist:latest
    steps:
      - uses: linogaliana/python-datascientist-actions/compile-all@v1.0.120
  deploy:
    name: Render-Blog
    runs-on: ubuntu-latest
    container: linogaliana/python-datascientist:minimal
    needs: [markdownise-manipulation, markdownise-visualisation, markdownise-modelisation,markdownise-nlp, markdownise-reste]
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
    steps:
      - uses: linogaliana/python-datascientist-actions/hugo-netlify@v1.0.120
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          alias: ${{ github.event.pull_request.head_ref }}
      - uses: actions/upload-artifact@v2
        with:
          name: Website [public]
          path: public/
          retention-days: 2
      - uses: actions/upload-artifact@v2
        with:
          name: Source files
          path: .
          retention-days: 2
  notebook-enonces:
    name: Conversion énoncés en notebooks Jupyter
    needs: [markdownise-manipulation, markdownise-visualisation, markdownise-modelisation,markdownise-nlp, markdownise-reste]
    runs-on: ubuntu-latest
    container: linogaliana/python-datascientist:minimal
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{github.event.pull_request.head.repo.full_name}}
      - uses: linogaliana/python-datascientist-actions/get-artifacts@v1.0.120
      - uses: linogaliana/python-datascientist-actions/convert-jupyter@v1.0.120
        with:
          directory-name: "notebooks"
          BRANCHE_REF: ${{ github.event.pull_request.head.ref }}
  markdownise-manipulation-corrections:
    name: Partie manipulation  [corrections]
    runs-on: ubuntu-latest
    container: linogaliana/python-datascientist:latest
    steps:
      - uses: linogaliana/python-datascientist-actions/compile@v1.0.120
        with:
          directory-name: 'manipulation'
          modify-chunk: true
          suffix: '-corrections'
  markdownise-visualisation-corrections:
    name: Partie visualisation  [corrections]
    runs-on: ubuntu-latest
    container: linogaliana/python-datascientist:latest
    steps:
      - uses: linogaliana/python-datascientist-actions/compile@v1.0.120
        with:
          directory-name: 'visualisation'
          modify-chunk: true
          suffix: '-corrections'
  markdownise-modelisation-corrections:
    name: Partie modélisation  [corrections]
    runs-on: ubuntu-latest
    container: linogaliana/python-datascientist:latest
    steps:
      - uses: linogaliana/python-datascientist-actions/compile@v1.0.120
        with:
          directory-name: 'modelisation'
          modify-chunk: true
          suffix: '-corrections'
  markdownise-nlp-corrections:
    name: Partie NLP  [corrections]
    runs-on: ubuntu-latest
    container: linogaliana/python-datascientist:latest
    steps:
      - uses: linogaliana/python-datascientist-actions/compile@v1.0.120
        with:
          directory-name: 'NLP'
          suffix: '-corrections'
  markdownise-reste-corrections:
    name: Markdown non thématiques [corrections]
    runs-on: ubuntu-latest
    container: linogaliana/python-datascientist:latest
    steps:
      - uses: linogaliana/python-datascientist-actions/compile-all@v1.0.120
        with:
          suffix: '-corrections'
  notebooks-corrections:
    name: Conversion corrections en notebooks Jupyter
    runs-on: ubuntu-latest
    container: linogaliana/python-datascientist:minimal
    needs: [markdownise-manipulation-corrections, markdownise-visualisation-corrections, markdownise-modelisation-corrections, markdownise-nlp-corrections, markdownise-reste-corrections]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{github.event.pull_request.head.repo.full_name}}
      - uses: linogaliana/python-datascientist-actions/get-artifacts@v1.0.120
        with:
          suffix: '-corrections'
          directory: "temp"
      - uses: linogaliana/python-datascientist-actions/convert-jupyter@v1.0.120
        with:
          directory-name: "corrections"
          BRANCHE_REF: ${{ github.event.pull_request.head.ref }}
