name: Docker Build and Website Deploy

on:
  push:
    branches:
      - main
      - master
      - light-action

jobs:
  blogdown:
    name: Render-Blog
    runs-on: ubuntu-latest
    container: linogaliana/python-datascientist:latest
    if: "!contains(github.event.commits[0].message, '[skip ci]')"
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - name: Check python installed
        run: |
          conda info
          conda list
        shell: bash
      - name: Build to md
        run: |
          Rscript -e 'source("./build/build.R")'
      - name: Clean files with Python function
        run: |
         pip install matplotlib wordcloud nltk
         python build/cleanmd.py
         python build/wc_website.py
      - name: Check hugo installed
        run: |
          rm -rf /usr/bin/hugo
          Rscript -e 'blogdown::install_hugo("0.83.0", force = TRUE)'
          Rscript -e 'print(blogdown:::hugo_version())'
        shell: bash
      - name: Render blog
        run: |
          ls
          find ./content -name "*.md" -type f
          Rscript -e 'source("./build/netlify.R")'
        shell: bash
      - name: Install npm
        if: ${{ github.repository == 'linogaliana/python-datascientist' }}
        uses: actions/setup-node@v2          
        with:
          node-version: '12'        
      - name: Deploy to Netlify
        if: ${{ github.repository == 'linogaliana/python-datascientist' }}
        # NETLIFY_AUTH_TOKEN and NETLIFY_SITE_ID added in the repo's secrets
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          BRANCHE_REF: ${{ github.event.pull_request.head.ref }}
        run: |
          npm init -y
          npm install --unsafe-perm=true netlify-cli -g
          #netlify deploy --prod --dir="public" --message "Deploy master"
          netlify deploy --alias=${BRANCHE_REF} --dir="public" --message "Preview deploy from ${BRANCHE_REF}"
      - uses: actions/upload-artifact@v1
        with:
          name: public
          path: public/